import type { Industry } from "./types";

export const industries: Industry[] = [
  {
    slug: "healthcare",
    title: "Healthcare",
    summary: "Patient-facing apps and clinical workflow tools.",
    headline: "Software for care teams that have no time to waste.",
    intro: "Booking, records, communication and coordination, designed for clarity under pressure and built with privacy as a starting condition.",
    challenges: [
      { title: "Fragmented systems", body: "Scheduling, records and messaging sit in separate tools that don't talk to each other." },
      { title: "Privacy obligations", body: "Patient data demands strict access control, auditing and secure hosting." },
      { title: "Time-poor users", body: "Clinicians won't tolerate interfaces that add clicks to a busy day." },
    ],
    solutions: [
      { title: "Unified workflows", body: "Booking, intake and follow-up connected in one coherent system." },
      { title: "Privacy by design", body: "Role-based access, audit logs and encrypted storage from the first commit." },
      { title: "Clinician-first UX", body: "Interfaces tested with the people who will use them daily." },
    ],
    features: ["Appointment booking", "Patient portals", "Secure messaging", "Intake forms", "Clinical dashboards", "Reminders and follow-ups"],
    tech: ["Next.js", "Python", "PostgreSQL", "AWS"],
    faqs: [
      { q: "Do you build to healthcare compliance standards?", a: "We design for your regulatory context, such as access control, audit trails and data residency. Formal certification depends on your organisation and hosting, and we scope it with you." },
      { q: "Can you integrate with existing clinical systems?", a: "Where those systems expose APIs or standard interfaces, yes. We assess feasibility during discovery." },
    ],
    workTags: ["Mobile", "Web", "Custom Software"],
    seoDescription: "Healthcare software development: patient portals, booking and clinical workflow tools built with privacy first.",
  },
  {
    slug: "fintech",
    title: "FinTech",
    summary: "Payments, accounting and financial workflow platforms.",
    headline: "Financial software where accuracy is the feature.",
    intro: "Ledgers, reconciliation, payments and reporting, engineered with audit trails and correctness at the centre.",
    challenges: [
      { title: "Correctness above all", body: "A rounding error or duplicate transaction is a trust problem, not a bug." },
      { title: "Integration sprawl", body: "Banks, payment providers and accounting tools each behave differently." },
      { title: "Security expectations", body: "Customers expect strong authentication and complete audit history." },
    ],
    solutions: [
      { title: "Ledger-grade data models", body: "Immutable records, double-entry logic and reconciliation built in." },
      { title: "Reliable integrations", body: "Idempotent, monitored connections to providers and banks." },
      { title: "Auditability", body: "Every change is recorded and explainable." },
    ],
    features: ["Multi-tenant ledgers", "Reconciliation", "Invoicing", "Payment integrations", "Approval workflows", "Reporting and exports"],
    tech: ["Python", "FastAPI", "PostgreSQL", "AWS"],
    faqs: [
      { q: "Can you build financial products for regulated markets?", a: "We build the software. Regulatory licences and compliance programmes remain your responsibility, and we design systems that support them." },
      { q: "Do you integrate with accounting platforms?", a: "Yes, through their official APIs where available." },
    ],
    workTags: ["SaaS", "AI", "Web"],
    seoDescription: "FinTech software development: multi-tenant ledgers, reconciliation and payment integrations.",
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    summary: "Listing platforms, property management and CRM.",
    headline: "Property platforms that move deals forward.",
    intro: "Listings, enquiries, viewings, tenancy and reporting, in systems that agents and managers actually keep up to date.",
    challenges: [
      { title: "Scattered enquiries", body: "Leads arrive by phone, email and portals and get lost between them." },
      { title: "Manual paperwork", body: "Agreements, inspections and payments run on documents and reminders." },
      { title: "Outdated listings", body: "Data drifts between website, CRM and portals." },
    ],
    solutions: [
      { title: "One lead pipeline", body: "Every enquiry captured, assigned and tracked to outcome." },
      { title: "Automated workflows", body: "Reminders, documents and payments handled by the system." },
      { title: "Single source of truth", body: "Property data managed once, published everywhere." },
    ],
    features: ["Listing management", "Search and filters", "Lead CRM", "Viewing scheduling", "Tenant portals", "Reporting"],
    tech: ["Next.js", "Python", "PostgreSQL"],
    faqs: [
      { q: "Can you integrate with listing portals?", a: "Where portals offer feeds or APIs, yes." },
      { q: "Do you build tenant and owner portals?", a: "Yes, with secure access to statements, requests and documents." },
    ],
    workTags: ["Web", "Custom Software", "Mobile"],
    seoDescription: "Real estate software development: listing platforms, property CRM and tenant portals.",
  },
  {
    slug: "education",
    title: "Education",
    summary: "Learning platforms and institutional tools.",
    headline: "Learning platforms people finish.",
    intro: "Course delivery, progress tracking, administration and communication, designed for learners and the staff who support them.",
    challenges: [
      { title: "Low completion", body: "Learners drop off when the experience is confusing or impersonal." },
      { title: "Administrative load", body: "Enrolment, grading and reporting consume staff time." },
      { title: "Diverse devices", body: "Users learn on whatever device they have, often on poor connections." },
    ],
    solutions: [
      { title: "Focused learner journeys", body: "Clear progress, sensible pacing and useful feedback." },
      { title: "Admin automation", body: "Enrolment, reminders and reporting handled by the system." },
      { title: "Accessible by default", body: "Works across devices and assistive technologies." },
    ],
    features: ["Course delivery", "Progress tracking", "Assessments", "Cohort management", "Payments", "Analytics"],
    tech: ["Next.js", "Python", "PostgreSQL"],
    faqs: [
      { q: "Can you build a marketplace for courses?", a: "Yes, including instructor onboarding, payments and payouts." },
      { q: "Can AI support learners?", a: "It can, for tutoring and search grounded in your course material, with clear boundaries and human oversight." },
    ],
    workTags: ["Web", "AI", "Mobile"],
    seoDescription: "Education software development: learning platforms, admin tools and learner apps.",
  },
  {
    slug: "retail",
    title: "Retail & E-commerce",
    summary: "Storefronts, ordering and inventory systems.",
    headline: "Commerce that stays fast on the busiest day.",
    intro: "Storefronts, wholesale ordering, inventory and fulfilment, built for speed and connected to the systems behind the counter.",
    challenges: [
      { title: "Slow storefronts", body: "Every extra second costs conversions, especially on mobile." },
      { title: "Inventory mismatch", body: "Stock shown online doesn't match stock on the shelf." },
      { title: "Platform limits", body: "Hosted platforms constrain pricing rules, B2B flows and integrations." },
    ],
    solutions: [
      { title: "Performance-first frontends", body: "Fast pages, streamlined checkout and clear product presentation." },
      { title: "Connected stock", body: "Inventory and orders synchronised across channels." },
      { title: "Custom commerce logic", body: "Tiered pricing, account ordering and approvals when you need them." },
    ],
    features: ["Custom storefronts", "B2B ordering", "Inventory sync", "Payments", "Order tracking", "Admin dashboards"],
    tech: ["Next.js", "Python", "PostgreSQL", "Redis"],
    faqs: [
      { q: "Do you work with Shopify or WooCommerce?", a: "We can integrate with or build alongside them, or build fully custom commerce when the requirements call for it." },
      { q: "Can you build B2B ordering portals?", a: "Yes, with account pricing, reorder flows and approvals." },
    ],
    workTags: ["E-commerce", "Web", "Mobile"],
    seoDescription: "Retail and e-commerce development: fast storefronts, B2B ordering and inventory integrations.",
  },
  {
    slug: "hospitality",
    title: "Hospitality",
    summary: "Booking, guest experience and operations tools.",
    headline: "Guest experiences that feel effortless from the first tap.",
    intro: "Reservations, guest communication, staff coordination and reporting, designed for teams working at full speed.",
    challenges: [
      { title: "Channel juggling", body: "Bookings arrive through many channels and must be reconciled." },
      { title: "Peak-time pressure", body: "Tools must be fast and forgiving when the venue is full." },
      { title: "Guest expectations", body: "Guests expect instant, personal communication." },
    ],
    solutions: [
      { title: "Unified booking", body: "One view of availability and reservations." },
      { title: "Staff-friendly tools", body: "Mobile interfaces built for fast use on the floor." },
      { title: "Guest communication", body: "Timely confirmations, updates and feedback capture." },
    ],
    features: ["Reservations", "Guest apps", "Staff scheduling", "Order flows", "Loyalty", "Reporting"],
    tech: ["Next.js", "Python", "PostgreSQL"],
    faqs: [
      { q: "Can you integrate with our POS?", a: "Where the POS provides an API, yes." },
      { q: "Do you build guest-facing mobile apps?", a: "Yes, for booking, ordering and loyalty." },
    ],
    workTags: ["Mobile", "Web", "Custom Software"],
    seoDescription: "Hospitality software: reservations, guest apps and staff operations tools.",
  },
  {
    slug: "logistics",
    title: "Logistics",
    summary: "Dispatch, tracking and operations platforms.",
    headline: "Operations software that keeps freight and fleets moving.",
    intro: "Dispatch, tracking, documentation and reporting in one operational view, reachable from the office and from the road.",
    challenges: [
      { title: "Manual dispatch", body: "Planning by phone and spreadsheet doesn't scale." },
      { title: "Limited visibility", body: "Customers and managers can't see where things are." },
      { title: "Paper trails", body: "Proof of delivery and documents are slow to collect." },
    ],
    solutions: [
      { title: "Operations platform", body: "Planning, assignment and status in one system." },
      { title: "Driver mobile apps", body: "Jobs, navigation hand-off and proof of delivery on the road." },
      { title: "Live reporting", body: "Dashboards that show what is happening now." },
    ],
    features: ["Dispatch and scheduling", "Driver apps", "Tracking", "Proof of delivery", "Customer portals", "Reporting"],
    tech: ["Python", "Django", "PostgreSQL", "AWS"],
    faqs: [
      { q: "Can you integrate with telematics?", a: "Where devices or providers expose APIs, yes." },
      { q: "Do drivers need constant connectivity?", a: "No. We design driver apps to work offline and sync later." },
    ],
    workTags: ["Custom Software", "Mobile", "Web"],
    seoDescription: "Logistics software development: dispatch platforms, driver apps and live operations dashboards.",
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    summary: "Client portals, practice tools and AI for knowledge work.",
    headline: "Systems for firms whose product is expertise.",
    intro: "Client portals, document workflows, time and billing, and AI assistants that give professionals their hours back.",
    challenges: [
      { title: "Document overload", body: "Client information arrives as files and emails that must be chased and filed." },
      { title: "Repetitive admin", body: "Skilled people spend time on tasks a system could handle." },
      { title: "Multi-client complexity", body: "Each client needs isolated data and tailored workflows." },
    ],
    solutions: [
      { title: "Client portals", body: "Secure upload, requests and status visibility." },
      { title: "Workflow automation", body: "Checklists, reminders and approvals encoded in software." },
      { title: "AI assistance", body: "Extraction, summarisation and search grounded in your firm's documents." },
    ],
    features: ["Client portals", "Document workflows", "Task management", "Time and billing", "AI document processing", "Practice reporting"],
    tech: ["Next.js", "Python", "FastAPI", "PostgreSQL", "LLMs"],
    faqs: [
      { q: "Can you build multi-tenant platforms for firms?", a: "Yes. Each firm's data is isolated and configurable." },
      { q: "Is AI safe for client data?", a: "With permission-aware retrieval, provider controls and logging, yes. We design this carefully and explain the trade-offs." },
    ],
    workTags: ["SaaS", "AI", "Custom Software"],
    seoDescription: "Software for professional services: client portals, workflow automation and AI document processing.",
  },
];

export const getIndustry = (slug: string) => industries.find((i) => i.slug === slug);
